/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fraction;

import fraction.Fraction;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class FractionTest {
    @Test void creation() {
        Fraction fraction = new Fraction();
        assertEquals(0, fraction.getNumerator());
    }
}
